baseURL = "https://www.opfinderklubben.dk/"
#languageCode = "sv"
defaultContentLanguage = "da"
title = "Opfinderklubben.dk"
theme = "ananke"
#SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-D0B2JX5X67"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = ""
  favicon = "images/favicon.ico"
  #site_logo = "images/opfinderklubben_logo_white_50px.svg"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-opfinderklubben-red"
  body_classes = "logo-bg titillum bg-near-white"
  post_content_classes = " bg-near-white"
  custom_css = ["custom.css", "fonts.css"]
  # ABout fonts:
  # https://github.com/tachyons-css/tachyons/blob/v4.7.0/src/_font-family.css
  recent_posts_number = 3
  commentoEnable = false
  #toc = true

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/opfinderklubben"

#[[params.ananke_socials]]
#name = "gitlab"
#url = "https://gitlab.com/opfinderklubben"

#[[menu.main]]
#    name = "Klubhuset"
#    weight = 10
#    identifier = "klubhuset"
#    url = "/page/klubhuset"

#[[menu.main]]
#    name = "Programmering for børn og unge"
#    weight = 20
#    identifier = "programmering-for-born"
#   url = "/page/programmering-for-born"